-- https://sqliteonline.com/

CREATE TABLE DATA_MARCA(
  COD_MARCA INTEGER,
  DESCRICION VARCHAR);

INSERT INTO DATA_MARCA VALUES ('1','NIKE'),('2','ADIDAS'),('3','PUMAS');
INSERT INTO DATA_PRODUCTOS VALUES ('1','1','1','VENTA1'),('2','2','2','VENTA2'),('3','2','2','VENTA3');
INSERT INTO DATA_MOVIMIENTOS VALUES ('1','1','2021-01-08','1','1','1'),('2','2','2021-01-08','1','1','1'),('3','3','2021-01-08','1','1','1');

CREATE TABLE DATA_PROVEEDORES(
  COD_PROVEEDOR INTEGER,
  DESCRIPCION VARCHAR)

CREATE TABLE DATA_CLIENTES(
  COD_CLIENTE INTEGER,
  DESCRIPCION VARCHAR)

create TABLE DATA_PRODUCTOS(
  COD_PROD INTEGER,
  COD_MARCA INTEGER,
  COD_PROVEEDOR INTEGER,
  DESCRIPCION VARCHAR)

create TABLE DATA_MOVIMIENTOS(
  COD_PROD INTEGER,
  COD_CLIENTE INTEGER,
  FECHA DATE,
  CANTIDAD DECIMAL,
  COSTO DECIMAL,
  VENTA DECIMAL)

SELECT dmar.cod_marca, dmar.descricion FROM (
    SELECT 
       dprod.cod_marca
    FROM DATA_MOVIMIENTOS AS dmov
    INNER JOIN DATA_PRODUCTOS AS dprod
        ON dmov.cod_prod = dprod.cod_prod
  	GROUP BY dprod.cod_marca
) AS join1
RIGHT JOIN DATA_MARCA AS dmar
    ON dmar.cod_marca = join1.cod_marca
    WHERE join1.cod_marca IS NULL

